CREATE TABLE IF NOT EXISTS bikinsomething (
	id BIGSERIAL PRIMARY KEY,
	name VARCHAR(256) NOT NULL,
	created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
	updated_at TIMESTAMP(0) WITH TIME ZONE NOT NULL DEFAULT NOW(),
	deleted_at TIMESTAMP(0) WITH TIME ZONE
);

DROP TABLE IF EXISTS bikinsomething;
	